spring.datasource.url=jdbc:postgresql://postgres:5432/trainerdb
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.show-sql=false


spring.data.mongodb.uri=mongodb://mongo:27017/trainer-workload-db

eureka.client.enabled=false
spring.jms.listener.auto-startup=false
spring.jms.pub-sub-domain=false
spring.jms.enabled=false
management.health.jms.enabled=false


