#spring.data.mongodb.uri=mongodb://mongo:27017/trainer-workload-db
spring.data.mongodb.uri=mongodb://localhost:27017/trainer-workload-db

eureka.client.enabled=false

# AWS Config
spring.cloud.aws.region.static=us-east-1
aws.profile=ec2_full_user

app.sqs.main-queue-url=https://sqs.us-east-1.amazonaws.com/663264486623/MyApp-Queue
app.sqs.dlq-url=https://sqs.us-east-1.amazonaws.com/663264486623/MyApp-Queue-DLQ
aws.sqs.dlqUrl=${app.sqs.dlq-url}         # your controller reads this

logging.level.software.amazon.awssdk=INFO
