spring.application.name=trainer-workload-service
server.port=8081

# Active profile
spring.profiles.active=minimal

# Logging and error
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.error.include-message=always
server.error.whitelabel.enabled=false

# Enable actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

security.jwt.hmacSecret=vR7xP9m$Jk3!qW@fYzL2bNcT#H8sAe4D





