aws.profile=ec2_full_user

eureka.client.enabled=false

# AWS Config
spring.cloud.aws.region.static=us-east-1

aws.sqs.queueUrl=https://sqs.us-east-1.amazonaws.com/663264486623/MyApp-Queue
app.sqs.main-queue-url=https://sqs.us-east-1.amazonaws.com/663264486623/MyApp-Queue
app.sqs.dlq-url=https://sqs.us-east-1.amazonaws.com/663264486623/MyApp-Queue-DLQ
aws.sqs.dlqUrl=${app.sqs.dlq-url}         # your controller reads this

app.dynamodb.table=TrainerReports

#logging.level.software.amazon.awssdk=INFO
#logging.level.io.awspring.cloud.sqs=DEBUG
#logging.level.software.amazon.awssdk.auth=DEBUG
