#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/gymcrm
#spring.datasource.url=jdbc:postgresql://localhost:5432/gymcrm
spring.datasource.url=jdbc:postgresql://postgres:5432/gymcrm
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.show-sql=false

spring.data.redis.port=6379
#spring.data.redis.host=host.docker.internal # used without integrating into docker
#spring.data.redis.host=localhost
spring.data.redis.host=redis


eureka.client.enabled=false
management.health.jms.enabled=false
