spring.application.name=main-app
jwt.secret=vR7xP9m$Jk3!qW@fYzL2bNcT#H8sAe4D

# Active profile
spring.profiles.active=docker

# Shared config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.jpa.repositories.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Logging and error
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.error.include-message=always
server.error.whitelabel.enabled=false

# Actuator exposure
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

# Prometheus
management.prometheus.metrics.export.enabled=true


