spring.datasource.url=jdbc:postgresql://localhost:5432/gymcrm
#spring.datasource.url=jdbc:postgresql://postgres:5432/gymcrm

# RDS
#spring.datasource.url=jdbc:postgresql://myapp-db.cqx0umkg6d1r.us-east-1.rds.amazonaws.com:5432/gymcrm
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.show-sql=false

spring.data.redis.port=6379
#spring.data.redis.host=host.docker.internal # used without integrating into docker
spring.data.redis.host=localhost
#spring.data.redis.host=redis

eureka.client.enabled=false

# AWS Config
spring.cloud.aws.region.static=us-east-1
aws.profile=ec2_full_user
aws.sqs.queueUrl=https://sqs.us-east-1.amazonaws.com/663264486623/MyApp-Queue

# optional: debug AWS SDK
logging.level.software.amazon.awssdk=INFO
